### ISSUE TITLE
Can't make map_arch to work

### ISSUE THREAD

**Issue by albarema** [YingZhou001/sprimepipeline#1]
Hi, 

I am getting this problem and I haven't been able to solve it. Do you have some hints on how to do it? "../tools/map_arch_genome/map_arch: Permission denied"

If I run _make_ in the map_arch directory I get a bunch of error related to gzFile and others. 

Thanks!!

Best, 
Alba!

**Comment by YingZhou001** [comment]
Sorry to reply late.
1. You can try "chmod +X map_arch" to let the program have executing permission. 
2. You may need to contact your system administrator to install the zlib library into your system. https://zlib.net/

Best,
Ying
